const topics = [
  "Zoology",
  "Astronomy",
  "Geography",
  "Botany",
  "Oceanography",
  "History",
  "Psychology",
  "Physics",
  "Mathematics",
  "Music",
  "Archaeology",
  "Engineering",
  "Technology",
  "Medicine",
  "Economics",
  "Linguistics",
  "Sports",
  "Art",
  "Anthropology",
  "Neuroscience",
  "Chemistry",
  "Mythology",
  "Literature",
  "Space Exploration",
  "Political Science",
  "Technology",
  "Physics",
  "Environmental Science",
  "Astronomy",
  "Astronomy",
  "Physics",
  "Cryptography",
  "Economics",
  "Geology",
  "Chemistry",
  "Botany",
  "Zoology",
  "Astronomy",
  "Medicine",
  "Psychology",
  "Physics",
  "Mathematics",
  "History",
  "Technology",
  "Philosophy",
  "Cultural Studies",
  "Environmental Science",
  "Astronomy",
  "Physics",
  "Geography",
  "Oceanography",
  "Geology",
  "Botany",
  "Anthropology",
  "Psychology",
  "Physics",
  "Astronomy",
  "Technology",
  "Neuroscience",
  "Art",
  "Linguistics",
  "Sports",
  "Technology",
  "Economics",
  "Botany",
  "Space Exploration",
  "Philosophy",
  "History",
  "Astronomy",
  "Technology",
  "Economics",
  "Physics",
  "Cultural Studies",
  "Psychology",
  "Mathematics",
  "Sports",
  "Astronomy",
  "Medicine",
  "Botany",
  "Art",
  "Psychology",
  "Technology",
  "Environmental Science",
  "History",
  "Geography",
  "Linguistics",
  "Economics",
  "Astronomy",
  "Physics",
  "Neuroscience",
  "Sports",
  "Chemistry",
  "Psychology",
  "Space Exploration",
  "Geology",
  "Cultural Studies",
  "Technology",
  "Art",
  "Botany",
  "Linguistics",
  "Environmental Science",
  "Zoology",
  "Technology",
  "Geography",
  "Space Exploration",
  "Astronomy",
  "Physics",
  "Neuroscience",
  "Sports",
  "Cultural Studies",
  "Linguistics",
  "Engineering",
  "History",
  "Psychology",
  "Economics",
  "Astronomy"
]

export default topics