const topics = [
  "Zoology: The Migration Patterns of Monarch Butterflies",
  "Astronomy: The Life Cycle of Stars",
  "Geography: The Longest River in Africa",
  "Botany: The Fastest Growing Plant in the World",
  "Oceanography: The Deepest Part of the Ocean",
  "History: The Origin of Ancient Egyptian Pyramids",
  "Psychology: The Concept of Cognitive Dissonance",
  "Physics: The Theory of Quantum Entanglement",
  "Mathematics: The Golden Ratio in Nature",
  "Music: The Role of Harmony in Classical Compositions",
  "Archaeology: The Discovery of Pompeii",
  "Engineering: The Construction of the Great Wall of China",
  "Technology: The History of the First Computer",
  "Medicine: The Role of DNA in Genetic Diseases",
  "Economics: The Concept of Supply and Demand",
  "Linguistics: The Evolution of the English Language",
  "Sports: The History of the Olympic Games",
  "Art: The Use of Perspective in Renaissance Paintings",
  "Anthropology: The Development of Human Tool Use",
  "Neuroscience: The Function of the Hippocampus",
  "Chemistry: The Periodic Table of Elements",
  "Mythology: The Origin of the Greek Gods",
  "Literature: The Themes of Shakespeare's Tragedies",
  "Space Exploration: The Apollo 11 Moon Landing",
  "Political Science: The Development of Democracy",
  "Technology: The Evolution of Smartphones",
  "Physics: The Theory of Relativity",
  "Environmental Science: The Impact of Climate Change on Coral Reefs",
  "Astronomy: The Existence of Exoplanets",
  "Astronomy: The Search for Extraterrestrial Life",
  "Physics: The Principle of Conservation of Energy",
  "Cryptography: The History of Encryption",
  "Economics: The Impact of Inflation on Purchasing Power",
  "Geology: The Formation of Volcanoes",
  "Chemistry: The Chemical Properties of Water",
  "Botany: The Process of Photosynthesis",
  "Zoology: The Anatomy of a Dolphin",
  "Astronomy: The Concept of Black Holes",
  "Medicine: The Development of Vaccines",
  "Psychology: The Influence of Childhood Experiences on Personality",
  "Physics: The Phenomenon of Light Refraction",
  "Mathematics: The Proof of Fermat's Last Theorem",
  "History: The Role of the Silk Road in Trade",
  "Technology: The History of the Internet",
  "Philosophy: The Concept of Free Will",
  "Cultural Studies: The Influence of Ancient Rome on Modern Society",
  "Environmental Science: The Role of Bees in Pollination",
  "Astronomy: The Concept of Dark Matter",
  "Physics: The Principle of Quantum Superposition",
  "Geography: The Formation of Mountains",
  "Oceanography: The Role of the Gulf Stream in Climate Regulation",
  "Geology: The Age of the Earth",
  "Botany: The Differences Between Angiosperms and Gymnosperms",
  "Anthropology: The Evolution of Early Human Societies",
  "Psychology: The Theory of Motivation",
  "Physics: The Concept of Time Dilation",
  "Astronomy: The Hubble Space Telescope Discoveries",
  "Technology: The Impact of Artificial Intelligence on Society",
  "Neuroscience: The Function of the Prefrontal Cortex",
  "Art: The Influence of Impressionism on Modern Art",
  "Linguistics: The Origins of Indo-European Languages",
  "Sports: The Evolution of the Soccer Ball",
  "Technology: The Invention of the Telephone",
  "Economics: The Role of Central Banks in Inflation Control",
  "Botany: The Lifespan of Giant Sequoias",
  "Space Exploration: The Launch of the Hubble Space Telescope",
  "Philosophy: The Ideas of Existentialism",
  "History: The Causes of World War I",
  "Astronomy: The Characteristics of Neutron Stars",
  "Technology: The Development of Electric Cars",
  "Economics: The Impact of Globalization on Local Economies",
  "Physics: The Concept of Wave-Particle Duality",
  "Cultural Studies: The Role of Storytelling in Different Cultures",
  "Psychology: The Concept of Emotional Intelligence",
  "Mathematics: The Concept of Fractals in Nature",
  "Sports: The Evolution of the Tennis Racket",
  "Astronomy: The Life Cycle of a Galaxy",
  "Medicine: The Role of Stem Cells in Regenerative Medicine",
  "Botany: The Reproduction of Ferns",
  "Art: The Use of Light in Photography",
  "Psychology: The Theory of Learning Styles",
  "Technology: The Development of Virtual Reality",
  "Environmental Science: The Role of Wetlands in Biodiversity",
  "History: The Rise and Fall of the Roman Empire",
  "Geography: The Influence of Ocean Currents on Weather Patterns",
  "Linguistics: The Study of Dialects",
  "Economics: The Theory of Economic Bubbles",
  "Astronomy: The Role of Supernovae in Star Formation",
  "Physics: The Concept of String Theory",
  "Neuroscience: The Relationship Between Brain and Behavior",
  "Sports: The Science of Athletic Performance",
  "Chemistry: The Creation of Synthetic Materials",
  "Psychology: The Impact of Social Media on Mental Health",
  "Space Exploration: The Search for Life on Mars",
  "Geology: The Process of Earthquakes",
  "Cultural Studies: The Traditions of Ancient Civilizations",
  "Technology: The Evolution of Video Game Consoles",
  "Art: The History of Graffiti as an Art Form",
  "Botany: The Medicinal Uses of Plants",
  "Linguistics: The Study of Phonetics",
  "Environmental Science: The Impact of Deforestation on Biodiversity",
  "Zoology: The Mating Rituals of Birds of Paradise",
  "Technology: The Rise of Electric Drones",
  "Geography: The Role of Deserts in Climate Regulation",
  "Space Exploration: The Search for Water on Other Planets",
  "Astronomy: The Effect of Solar Flares on Earth",
  "Physics: The Nature of Dark Energy",
  "Neuroscience: The Science of Memory Formation",
  "Sports: The Physics of Baseball",
  "Cultural Studies: The Influence of Global Cuisine on Local Cultures",
  "Linguistics: The History of Written Language",
  "Engineering: The Evolution of Suspension Bridges",
  "History: The Impact of the Industrial Revolution on Society",
  "Psychology: The Theory of Self-Actualization",
  "Economics: The Impact of Automation on Employment",
  "Astronomy: The Role of Asteroids in the Formation of the Solar System"
]

export default topics